GET http://localhost:8080/api/v1/tasks
Accept: application/json

###

GET http://localhost:8080/api/v1/tasks?priority=2
Accept: application/json

###

POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

[
  {
    "title": "Buy groceries",
    "status": "pending",
    "priority": 2
  }
]

###

POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

[
  {
    "title": "Walk the dog",
    "status": "done",
    "priority": 1
  },
  {
    "title": "Pay bills",
    "status": "pending",
    "priority": 3
  }
]

###

PUT http://localhost:8080/api/v1/tasks/1
Content-Type: application/json

{
  "status": "completed",
  "priority": 4
}

###

DELETE http://localhost:8080/api/v1/tasks/1

###

GET http://localhost:8080/api/v1/tasks/activity-log?limit=10&offset=1

